name: tarea_base_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  provider: ^6.0.5
  flutter_local_notifications: ^16.1.0
  intl: ^0.18.1
  flutter_datetime_picker_plus: ^2.1.0
  table_calendar: ^3.0.9
  flutter_slider_drawer: ^2.1.3
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/
